export enum PhysicalSymptoms {
  ColopathieFonctionnelle = 'ColopathieFonctionnelle',
  Nausee = 'Nausee',
  HyperphagieBoulimique = 'HyperphagieBoulimique',
  PerteDAppetit = 'PerteDAppetit',
  IncapaciteAManger = 'IncapaciteAManger',
  Douleurs = 'Douleurs',
  TensionsMusculaires = 'TensionsMusculaires',
  Fourmillements = 'Fourmillements',
  Palpitations = 'Palpitations',
  DouleursThoraciques = 'DouleursThoraciques',
  EnvieFrequenteDUriner = 'EnvieFrequenteDUriner',
  Insomnies = 'Insomnies',
  SomnolencesDansLaJournee = 'SomnolencesDansLaJournee',
  Fatigue = 'Fatigue',
  MalDeTete = 'MalDeTete',
  Vertiges = 'Vertiges',
  SensationDeFaiblesse = 'SensationDeFaiblesse',
}
